In [1]:
import numpy as np

arr = np.random.randint(1, 101, 20)

print("Исходный массив:")
print(arr)

elements_divisible_by_5 = arr[arr % 5 == 0]
print("\nЭлементы, делящиеся на 5:")
print(elements_divisible_by_5)

arr[arr % 5 == 0] = -1

print("\nОбновленный массив (элементы, делящиеся на 5, заменены на -1):")
print(arr)


Исходный массив:
[ 7 25 39 32 26 57 93 92 44 86 65 20 66 86 66 25 57  2  8 60]

Элементы, делящиеся на 5:
[25 65 20 25 60]

Обновленный массив (элементы, делящиеся на 5, заменены на -1):
[ 7 -1 39 32 26 57 93 92 44 86 -1 -1 66 86 66 -1 57  2  8 -1]
