In [1]:
import numpy as np

arr1 = np.random.randint(0, 51, size=(1, 5))
arr2 = np.random.randint(0, 51, size=(1, 5))

print("Первый массив:")
print(arr1)
print("\nВторой массив:")
print(arr2)

combined_arr = np.concatenate((arr1, arr2), axis=0)

print("\nОбъединенный массив:")
print(combined_arr)

arr_split1, arr_split2 = np.split(combined_arr, 2, axis=0)
print("\nПервый разделенный массив:")
print(arr_split1)
print("\nВторой разделенный массив:")
print(arr_split2)


Первый массив:
[[ 8 39 31  4  9]]

Второй массив:
[[ 8 48  6 15  6]]

Объединенный массив:
[[ 8 39 31  4  9]
 [ 8 48  6 15  6]]

Первый разделенный массив:
[[ 8 39 31  4  9]]

Второй разделенный массив:
[[ 8 48  6 15  6]]
