In [5]:
import numpy as np

# Создаем единичную матрицу размером 4x4
identity_matrix = np.eye(4)
print("Единичная матрица 4x4:")
print(identity_matrix)

# Создаем диагональную матрицу размером 4x4 с диагональными элементами [5, 10, 15, 20]
diagonal_elements = np.array([5, 10, 15, 20])
diagonal_matrix = np.diag(diagonal_elements)
print("\nДиагональная матрица 4x4:")
print(diagonal_matrix)

# Вычисляем суммы всех элементов в каждой матрице
identity_sum = np.sum(identity_matrix)
diagonal_sum = np.sum(diagonal_matrix)

# Выводим результаты
print("\nСумма всех элементов единичной матрицы:", identity_sum)
print("Сумма всех элементов диагональной матрицы:", diagonal_sum)

# Сравниваем результаты
if identity_sum > diagonal_sum:
    print("Сумма единичной матрицы больше суммы диагональной матрицы.")
elif identity_sum < diagonal_sum:
    print("Сумма диагональной матрицы больше суммы единичной матрицы.")
else:
    print("Суммы обеих матриц равны.")

Единичная матрица 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица 4x4:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сумма всех элементов единичной матрицы: 4.0
Сумма всех элементов диагональной матрицы: 50
Сумма диагональной матрицы больше суммы единичной матрицы.
