In [4]:
import numpy as np

# Создаем две матрицы 3x3 с случайными целыми числами от 1 до 20
matrix_a = np.random.randint(1, 21, size=(3, 3))
matrix_b = np.random.randint(1, 21, size=(3, 3))

print("Первая матрица (A):")
print(matrix_a)

print("\nВторая матрица (B):")
print(matrix_b)

# Вычисляем сумму матриц
matrix_sum = matrix_a + matrix_b

# Вычисляем разность матриц
matrix_difference = matrix_a - matrix_b

# Вычисляем поэлементное произведение матриц
elementwise_product = matrix_a * matrix_b

# Выводим результаты
print("\nСумма матриц (A + B):")
print(matrix_sum)

print("\nРазность матриц (A - B):")
print(matrix_difference)

print("\nПоэлементное произведение матриц (A * B):")
print(elementwise_product)

Первая матрица (A):
[[16  9  8]
 [ 5 17 10]
 [15  7  1]]

Вторая матрица (B):
[[20  9 16]
 [ 5  1  4]
 [ 4 11  8]]

Сумма матриц (A + B):
[[36 18 24]
 [10 18 14]
 [19 18  9]]

Разность матриц (A - B):
[[-4  0 -8]
 [ 0 16  6]
 [11 -4 -7]]

Поэлементное произведение матриц (A * B):
[[320  81 128]
 [ 25  17  40]
 [ 60  77   8]]
