In [1]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 3))

matrix2 = np.random.randint(1, 11, size=(3, 2))
print("Первая матрица (2x3):\n", matrix1)
print("\nВторая матрица (3x2):\n", matrix2)

result_matrix = matrix1 @ matrix2

print("\nРезультат матричного умножения (2x2):\n", result_matrix)


Первая матрица (2x3):
 [[10  3  1]
 [ 1  2  5]]

Вторая матрица (3x2):
 [[4 9]
 [3 9]
 [4 2]]

Результат матричного умножения (2x2):
 [[ 53 119]
 [ 30  37]]
