In [1]:
import numpy as np

matrix = np.random.rand(3, 3)

print("Исходная матрица:\n", matrix)

determinant = np.linalg.det(matrix)
print("\nОпределитель матрицы:", determinant)

if abs(determinant) > 1e-8:
    try:
        inverse_matrix = np.linalg.inv(matrix)
        print("\nОбратная матрица:\n", inverse_matrix)
    except np.linalg.LinAlgError:
        print("\nМатрица вырождена и не имеет обратной матрицы.")

else:
    print("\nМатрица вырождена и не имеет обратной матрицы.")


Исходная матрица:
 [[0.05554635 0.66490963 0.68912159]
 [0.69785546 0.50384752 0.747731  ]
 [0.00226231 0.38764827 0.68220259]]

Определитель матрицы: -0.12679499780252335

Обратная матрица:
 [[-0.42485469  1.47061224 -1.18270707]
 [ 3.74137159 -0.28656382 -3.46522767]
 [-2.12455231  0.15795747  3.43881013]]
