In [5]:
import numpy as np

# Создаем матрицу 4x4 с случайными целыми числами от 1 до 50
matrix = np.random.randint(1, 51, size=(4, 4))

print("Исходная матрица:")
print(matrix)

# Транспонируем матрицу
transposed_matrix = matrix.T
print("\nТранспонированная матрица:")
print(transposed_matrix)

# Вычисляем след матрицы (сумму элементов на главной диагонали)
matrix_trace = np.trace(matrix)
print("\nСлед матрицы (сумма элементов на главной диагонали):", matrix_trace)


Исходная матрица:
[[48  1 27 12]
 [28 34 38 12]
 [27 46 21 17]
 [12 35 47 21]]

Транспонированная матрица:
[[48 28 27 12]
 [ 1 34 46 35]
 [27 38 21 47]
 [12 12 17 21]]

След матрицы (сумма элементов на главной диагонали): 124
